---
title: Miranda Brooks Portfolio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  press:
    title: Press
    output: false
    bio-photo: "/uploads/Miranda-B-by-Ricardo-Labougle.jpg"
  seasons:
    title: Seasons
    output: true
    permalink: "/:title"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: seasons
  values:
    slideshow:
    - image: ''
      hover-title: ''
      horizontal: 50%
      vertical: 50%
sass:
  sass_dir: assets/css
permalink: pretty
season: 
slider-rate: 5000
slider-animation-speed: 600
imgurl: https://res.cloudinary.com/miranda-brooks-landscape-design/image/fetch
tempurl: http://mirandabrooks.com.s3-website-us-east-1.amazonaws.com
