---
title: Miranda Brooks Portfolio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  press:
    title: Press
    output: true
  seasons:
    title: Seasons
    output: true
    permalink: "/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
sass:
  sass_dir: assets/css
