---
title: MBLD
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  press:
    title: Press
    output: false
    bio-photo: "/uploads/MB-Web-sk3_Page_11_Image_0001.jpg"
  seasons:
    title: Seasons
    output: true
    permalink: "/:title"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: seasons
  values:
    slideshow:
    - image: ''
      hover-title: ''
      horizontal: 50%
      vertical: 50%
sass:
  sass_dir: assets/css
permalink: pretty
navigation: false
slider-rate: 5000
slider-animation-speed: 600
