---
title: Miranda Brooks Landscape Design
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  press:
    title: Press
    output: false
    bio-photo: "/uploads/Miranda-B-by-Ricardo-Labougle.jpg"
  seasons:
    title: Seasons
    output: true
    permalink: "/:title"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: seasons
  values:
    slideshow:
    - image: ''
      hover-title: ''
      horizontal: 50%
      vertical: 50%
description: Landscape Architect and American Vogue Contributing Editor
author: Miranda Brooks
season: Late Summer
sass:
  sass_dir: assets/css
permalink: pretty
slider-rate: 5000
slider-animation-speed: 600
imgurl: https://mirandabrooks.imgix.net
tempurl: http://mirandabrooks.com.s3-website-us-east-1.amazonaws.com
